### ISSUE TITLE
fix: Unable to make application using mason

### ISSUE THREAD

**Issue by dhirajhimani** [Arnooodles/domain_driven_bloc#21]
**Description**
Error: Unable to spawn isolate: Can't load Kernel binary: Invalid kernel binary format version.

**Steps To Reproduce**

mason make domain_driven_bloc

**Expected Behavior**
Able to make my_app without error

**Additional Context**
Flutter Version

Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (2 weeks ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1

**Comment by Arnooodles** [comment]
Hello @dhirajhimani, have you tried updating your mason `mason update` and also upgrading the bricks `mason upgrade`?

If this still does not work try `dart pub global deactivate mason_cli` and install it again `dart pub global activate mason_cli`

**Comment by dhirajhimani** [comment]
It seems I had mason installed from brew and dart, upgrading was doing upgrading the brew mason, but using the make command was using the dart make.|
Finally solved it, removed the brew mason, and now no issue. Thanks
